name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "adopt"
          cache: "gradle"
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: liquidbounce++
          path: build/libs/*.jar
          if-no-files-found: error
